#ifndef API_SERVER_H
#define API_SERVER_H

#ifdef __cplusplus
extern "C" {
#endif

/*
 * API Server Header
 * 
 * Requires Mongoose v7.20 or higher with MG_ENABLE_HTTP enabled.
 * 
 * This starts a simple HTTP API server on port 8000 and handles three endpoints:
 * 
 * 1. /book
 *    - Books a new ticket.
 *    - Request body must include: name, age, src, dest, berth.
 *    - Passenger ID is auto-generated by the backend.
 * 
 * 2. /cancel
 *    - Cancels a ticket by ID.
 *    - Request body must include: id.
 * 
 * 3. /search
 *    - Searches for a passenger by ID.
 *    - Request body must include: id.
 * 
 * Notes:
 * - This function blocks indefinitely in a polling loop.
 * - On Windows, WSADATA initialization is done internally using WSAStartup.
 */
void start_api_server(void);

#ifdef __cplusplus
}
#endif

#endif /* API_SERVER_H */
